### PR TITLE
Add oredict support to composter

### LINKED ISSUE #173: support oredict in the composter config
Hello :)

I am using the most current version of charm for minecraft 1.12.2 and I noticed that the composter only accepts vanilla seeds but not seeds added from other mods e.g. Flax seeds from actually additions. Now I am not sure if that is an error on my end and a configuration thing but I would like to report this.
I am not sure if you guys have to add support for every single seeds out there (which is impossible) or if there is something like a generic "seeds" object thing so that the composter can use seeds and plant parts for every mods.

Thank you very much

### PR DESCRIPTION
**Pull request by williambl**
Will close #173 when merged.

Entries can be added to the config file, prefixed with `ore:`. Entries are case-sensitive. I haven't added any entries to the default config file.

Video of it in action, with `ore:listAllseed` in the config file, and some Pam's Harvestcraft seeds: https://youtu.be/HUvnzWMfBNk

### CODE REVIEW

**Comment by svenhjol** [comment]
Hi, please could you resubmit this against the mc1.12 branch as master is now for tracking 1.14.4?

**Comment by williambl** [comment]
Done.

**Comment by svenhjol** [comment]
Thanks!

**Comment by williambl** [comment]
No problem.

**Pull request merged**
